services:
  postgres:
    image: postgres:16
    container_name: litellm_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./config.yml:/app/config.yaml
    env_file:
      - .env
    command:
      - "--config"
      - "/app/config.yaml"

volumes:
  postgres_data:
